services:
  node:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TOKEN=${TOKEN}
    develop:
     watch:
      - action: sync+restart
        path: .
        target: /code
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password